set dotenv-load

[no-cd]
develop:
  DEVENV_DIR=$(pwd) nix develop

env TYPE NAME:
  (cd ~/dev/src/{{TYPE}}/{{NAME}} && just -g develop)

[no-cd]
up *SERVICE:
  podman compose --file $DEVENV_PROJECT_ROOT/docker-compose.yml up --build -d {{SERVICE}}

[no-cd]
down *SERVICE:
  podman compose --file $DEVENV_PROJECT_ROOT/docker-compose.yml down {{SERVICE}}

[no-cd]
restart SERVICE:
  podman compose --file $DEVENV_PROJECT_ROOT/docker-compose.yml restart {{SERVICE}}

[no-cd]
log *SERVICE:
  podman compose --file $DEVENV_PROJECT_ROOT/docker-compose.yml logs --timestamps -f {{SERVICE}}

[no-cd]
create-bare-env NAME ENV:
  cp -r $NIXCONFIG/dev-envs/{{ENV}} {{NAME}}
  find {{NAME}}/ -type f | xargs -I{} sed -i s/projectname/{{NAME}}/g {}
  echo "DEVENV_PROJECT_ROOT=." >> {{NAME}}/.env
  echo "DEVENV_ABS_PATH=$(pwd)/{{NAME}}" >> {{NAME}}/.env

[no-cd]
create-env NAME REPO ENV:
  #!/usr/bin/env bash
  # TODO: run create-bare-env
  cp -r $NIXCONFIG/dev-envs/{{ENV}} {{NAME}}
  find {{NAME}}/ -type f | xargs -I{} sed -i s/projectname/{{NAME}}/g {}
  REPO_DIR_NAME=$(echo {{REPO}} | sed 's/\.git$//')
  echo "DEVENV_PROJECT_ROOT=$REPO_DIR_NAME" >> {{NAME}}/.env
  echo "$REPO_DIR_NAME/" >> {{NAME}}/.gitignore
  (cd {{NAME}} && git clone {{REPO}})

